FROM podbox/teamcity-agent
MAINTAINER Pawel Kobylak <noose@noose.pl>
RUN sed -i 's/serverUrl=http:\/\/teamcity:8080\/teamcity\//serverUrl=http:\/\/teamcity:8111\//'  /teamcity-agent/conf/buildAgent.properties
