postgres:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "teamcityPassword"
        POSTGRES_DB: "teamcity"
    volumes:
        - /var/lib/postgresql

teamcity:
    build: teamcity
    links: 
        - postgres
    ports:
        - 8111:8111

agent:
    build: teamcity-agent
    links:
        - teamcity

